/* Optional HL7 FHIR resource projection schema for local visibility. Canonical persistence remains Microsoft FHIR Server. */
USE FhirPlatform;
GO
IF OBJECT_ID('Hl7FhirResource', 'U') IS NULL
CREATE TABLE Hl7FhirResource (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'Resource', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirDomainResource', 'U') IS NULL
CREATE TABLE Hl7FhirDomainResource (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'DomainResource', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirBundle', 'U') IS NULL
CREATE TABLE Hl7FhirBundle (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'Bundle', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirOperationOutcome', 'U') IS NULL
CREATE TABLE Hl7FhirOperationOutcome (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'OperationOutcome', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirBinary', 'U') IS NULL
CREATE TABLE Hl7FhirBinary (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'Binary', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirParameters', 'U') IS NULL
CREATE TABLE Hl7FhirParameters (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'Parameters', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirImplementationGuide', 'U') IS NULL
CREATE TABLE Hl7FhirImplementationGuide (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'ImplementationGuide', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirSearchParameter', 'U') IS NULL
CREATE TABLE Hl7FhirSearchParameter (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'SearchParameter', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirOperationDefinition', 'U') IS NULL
CREATE TABLE Hl7FhirOperationDefinition (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'OperationDefinition', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirCompartmentDefinition', 'U') IS NULL
CREATE TABLE Hl7FhirCompartmentDefinition (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'CompartmentDefinition', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirStructureDefinition', 'U') IS NULL
CREATE TABLE Hl7FhirStructureDefinition (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'StructureDefinition', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirConsent', 'U') IS NULL
CREATE TABLE Hl7FhirConsent (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'Consent', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirProvenance', 'U') IS NULL
CREATE TABLE Hl7FhirProvenance (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'Provenance', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirAuditEvent', 'U') IS NULL
CREATE TABLE Hl7FhirAuditEvent (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'AuditEvent', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirCapabilityStatement', 'U') IS NULL
CREATE TABLE Hl7FhirCapabilityStatement (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'CapabilityStatement', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirCodeSystem', 'U') IS NULL
CREATE TABLE Hl7FhirCodeSystem (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'CodeSystem', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirValueSet', 'U') IS NULL
CREATE TABLE Hl7FhirValueSet (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'ValueSet', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirConceptMap', 'U') IS NULL
CREATE TABLE Hl7FhirConceptMap (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'ConceptMap', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirNamingSystem', 'U') IS NULL
CREATE TABLE Hl7FhirNamingSystem (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'NamingSystem', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirDocumentReference', 'U') IS NULL
CREATE TABLE Hl7FhirDocumentReference (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'DocumentReference', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirMessageHeader', 'U') IS NULL
CREATE TABLE Hl7FhirMessageHeader (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'MessageHeader', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirSubscription', 'U') IS NULL
CREATE TABLE Hl7FhirSubscription (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'Subscription', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirTask', 'U') IS NULL
CREATE TABLE Hl7FhirTask (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'Task', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirPatient', 'U') IS NULL
CREATE TABLE Hl7FhirPatient (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'Patient', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirPractitioner', 'U') IS NULL
CREATE TABLE Hl7FhirPractitioner (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'Practitioner', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirPractitionerRole', 'U') IS NULL
CREATE TABLE Hl7FhirPractitionerRole (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'PractitionerRole', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirCareTeam', 'U') IS NULL
CREATE TABLE Hl7FhirCareTeam (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'CareTeam', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirDevice', 'U') IS NULL
CREATE TABLE Hl7FhirDevice (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'Device', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirOrganization', 'U') IS NULL
CREATE TABLE Hl7FhirOrganization (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'Organization', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirLocation', 'U') IS NULL
CREATE TABLE Hl7FhirLocation (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'Location', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirHealthcareService', 'U') IS NULL
CREATE TABLE Hl7FhirHealthcareService (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'HealthcareService', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirEndpoint', 'U') IS NULL
CREATE TABLE Hl7FhirEndpoint (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'Endpoint', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirRelatedPerson', 'U') IS NULL
CREATE TABLE Hl7FhirRelatedPerson (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'RelatedPerson', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirAllergyIntolerance', 'U') IS NULL
CREATE TABLE Hl7FhirAllergyIntolerance (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'AllergyIntolerance', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirCondition', 'U') IS NULL
CREATE TABLE Hl7FhirCondition (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'Condition', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirProcedure', 'U') IS NULL
CREATE TABLE Hl7FhirProcedure (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'Procedure', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirCarePlan', 'U') IS NULL
CREATE TABLE Hl7FhirCarePlan (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'CarePlan', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirGoal', 'U') IS NULL
CREATE TABLE Hl7FhirGoal (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'Goal', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirServiceRequest', 'U') IS NULL
CREATE TABLE Hl7FhirServiceRequest (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'ServiceRequest', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirFamilyMemberHistory', 'U') IS NULL
CREATE TABLE Hl7FhirFamilyMemberHistory (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'FamilyMemberHistory', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirRiskAssessment', 'U') IS NULL
CREATE TABLE Hl7FhirRiskAssessment (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'RiskAssessment', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirClinicalImpression', 'U') IS NULL
CREATE TABLE Hl7FhirClinicalImpression (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'ClinicalImpression', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirComposition', 'U') IS NULL
CREATE TABLE Hl7FhirComposition (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'Composition', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirQuestionnaire', 'U') IS NULL
CREATE TABLE Hl7FhirQuestionnaire (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'Questionnaire', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirQuestionnaireResponse', 'U') IS NULL
CREATE TABLE Hl7FhirQuestionnaireResponse (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'QuestionnaireResponse', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirObservation', 'U') IS NULL
CREATE TABLE Hl7FhirObservation (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'Observation', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirDiagnosticReport', 'U') IS NULL
CREATE TABLE Hl7FhirDiagnosticReport (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'DiagnosticReport', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirSpecimen', 'U') IS NULL
CREATE TABLE Hl7FhirSpecimen (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'Specimen', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirImagingStudy', 'U') IS NULL
CREATE TABLE Hl7FhirImagingStudy (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'ImagingStudy', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirMedia', 'U') IS NULL
CREATE TABLE Hl7FhirMedia (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'Media', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirBodyStructure', 'U') IS NULL
CREATE TABLE Hl7FhirBodyStructure (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'BodyStructure', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirMolecularSequence', 'U') IS NULL
CREATE TABLE Hl7FhirMolecularSequence (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'MolecularSequence', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirMedication', 'U') IS NULL
CREATE TABLE Hl7FhirMedication (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'Medication', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirMedicationRequest', 'U') IS NULL
CREATE TABLE Hl7FhirMedicationRequest (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'MedicationRequest', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirMedicationDispense', 'U') IS NULL
CREATE TABLE Hl7FhirMedicationDispense (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'MedicationDispense', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirMedicationAdministration', 'U') IS NULL
CREATE TABLE Hl7FhirMedicationAdministration (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'MedicationAdministration', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirMedicationStatement', 'U') IS NULL
CREATE TABLE Hl7FhirMedicationStatement (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'MedicationStatement', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirAppointment', 'U') IS NULL
CREATE TABLE Hl7FhirAppointment (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'Appointment', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirSchedule', 'U') IS NULL
CREATE TABLE Hl7FhirSchedule (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'Schedule', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirSlot', 'U') IS NULL
CREATE TABLE Hl7FhirSlot (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'Slot', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirCommunication', 'U') IS NULL
CREATE TABLE Hl7FhirCommunication (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'Communication', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirCommunicationRequest', 'U') IS NULL
CREATE TABLE Hl7FhirCommunicationRequest (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'CommunicationRequest', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirEpisodeOfCare', 'U') IS NULL
CREATE TABLE Hl7FhirEpisodeOfCare (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'EpisodeOfCare', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirCoverage', 'U') IS NULL
CREATE TABLE Hl7FhirCoverage (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'Coverage', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirClaim', 'U') IS NULL
CREATE TABLE Hl7FhirClaim (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'Claim', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirClaimResponse', 'U') IS NULL
CREATE TABLE Hl7FhirClaimResponse (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'ClaimResponse', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirExplanationOfBenefit', 'U') IS NULL
CREATE TABLE Hl7FhirExplanationOfBenefit (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'ExplanationOfBenefit', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirInvoice', 'U') IS NULL
CREATE TABLE Hl7FhirInvoice (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'Invoice', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirAccount', 'U') IS NULL
CREATE TABLE Hl7FhirAccount (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'Account', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirChargeItem', 'U') IS NULL
CREATE TABLE Hl7FhirChargeItem (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'ChargeItem', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirPaymentNotice', 'U') IS NULL
CREATE TABLE Hl7FhirPaymentNotice (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'PaymentNotice', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirPaymentReconciliation', 'U') IS NULL
CREATE TABLE Hl7FhirPaymentReconciliation (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'PaymentReconciliation', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirLibrary', 'U') IS NULL
CREATE TABLE Hl7FhirLibrary (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'Library', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirPlanDefinition', 'U') IS NULL
CREATE TABLE Hl7FhirPlanDefinition (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'PlanDefinition', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirActivityDefinition', 'U') IS NULL
CREATE TABLE Hl7FhirActivityDefinition (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'ActivityDefinition', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirGuidanceResponse', 'U') IS NULL
CREATE TABLE Hl7FhirGuidanceResponse (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'GuidanceResponse', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirMeasure', 'U') IS NULL
CREATE TABLE Hl7FhirMeasure (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'Measure', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirMeasureReport', 'U') IS NULL
CREATE TABLE Hl7FhirMeasureReport (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'MeasureReport', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirEvidence', 'U') IS NULL
CREATE TABLE Hl7FhirEvidence (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'Evidence', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirEvidenceVariable', 'U') IS NULL
CREATE TABLE Hl7FhirEvidenceVariable (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'EvidenceVariable', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirResearchDefinition', 'U') IS NULL
CREATE TABLE Hl7FhirResearchDefinition (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'ResearchDefinition', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Hl7FhirResearchElementDefinition', 'U') IS NULL
CREATE TABLE Hl7FhirResearchElementDefinition (Id uniqueidentifier NOT NULL PRIMARY KEY, ResourceType nvarchar(128) NOT NULL DEFAULT 'ResearchElementDefinition', LogicalId nvarchar(256) NULL, VersionId nvarchar(128) NULL, LastUpdated datetimeoffset NULL, Identifier nvarchar(256) NULL, SubjectReference nvarchar(256) NULL, PatientReference nvarchar(256) NULL, Status nvarchar(128) NULL, Display nvarchar(512) NULL, CanonicalUrl nvarchar(max) NULL, ProfileUrls nvarchar(max) NULL, SecurityLabels nvarchar(max) NULL, Tags nvarchar(max) NULL, RawJson nvarchar(max) NULL, RawXml nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL DEFAULT SYSUTCDATETIME());
GO
